apiVersion: v1
kind: Service
metadata:
  name: lifeos-app
  namespace: lifeos
  labels:
    app.kubernetes.io/name: lifeos-app
    app.kubernetes.io/part-of: lifeos
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      name: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: lifeos-app
