apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lifeos

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - app-deployment.yaml
  - app-service.yaml
  - ingress.yaml
